export const theme = {
  colors: {
    appBackground: "#f6f3ee",
    surface: "#ffffff",
    surfaceMuted: "#eef1f6",
    surfaceSoft: "#fbfaf7",
    ink: "#243247",
    inkSoft: "#5d6c81",
    muted: "#8a94a2",
    border: "#e6dfd5",
    accent: "#f6b879",
    accentSoft: "#fff1df",
    success: "#9fd8a5",
    shadow: "rgba(36, 50, 71, 0.08)",
  },
  radius: {
    xl: 30,
    lg: 24,
    md: 18,
    sm: 14,
    pill: 999,
  },
  spacing: {
    xs: 6,
    sm: 10,
    md: 16,
    lg: 20,
    xl: 28,
  },
  status: {
    LOW_ENERGY: {
      label: "차분",
      bubble: "오늘은 천천히.",
      description: "오늘은 조용하고 흔들리지 않는 날이에요.",
      background: ["#f2f0ea", "#fbfaf6"],
      stage: "#f3efe5",
      bubbleSurface: "#f7f2e9",
      effect: "cloudy",
      animationSpeed: 0.72,
      bobAmount: 0.026,
    },
    NORMAL_ENERGY: {
      label: "평온",
      bubble: "도마에 맞춰 걷고 있어.",
      description: "오늘 상태는 안정적이고, 일반적으로 걸을 수 있는 분위기예요.",
      background: ["#f7f5ef", "#eef3f7"],
      stage: "#f3f4f8",
      bubbleSurface: "#f5f4fb",
      effect: "float",
      animationSpeed: 0.98,
      bobAmount: 0.044,
    },
    HIGH_ENERGY: {
      label: "활발",
      bubble: "왜쩍 더 걸어보고 싶어!",
      description: "오늘 에너지가 높아서 발걸음과 분위기가 더 살아나요.",
      background: ["#eef8ef", "#f7fcf4"],
      stage: "#edf8f0",
      bubbleSurface: "#edf8ef",
      effect: "sparkle",
      animationSpeed: 1.18,
      bobAmount: 0.06,
    },
  },
  growth: {
    WEAK: {
      label: "성장 초기",
      bubble: "아직 기본이 만들어지는 중이에요.",
      description: "누적 걸음이 아직 적어서 기본 형태가 천천히 자리잡는 상태예요.",
    },
    HEALTHY: {
      label: "건강",
      bubble: "서둘지 않아도 잘 맞아지고 있어.",
      description: "걸음이 커질수록 모습이 안정적이고 단단해지는 상태예요.",
    },
    ACTIVE: {
      label: "활동적",
      bubble: "움직임이 강하게 있어!",
      description: "오랜 시간 걸음이 쌓이는 만큼 더 두텁고 활발한 상태예요.",
    },
  },
} as const;

export type EnergyState = keyof typeof theme.status;
export type LongTermState = keyof typeof theme.growth;
